### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by brunowego**
#39

### CODE REVIEW

**Comment by nkbt** [comment]
I would put more info into this one. See package.json.

Also would prefer to keep bower-compatible compiled sources in a separate repo.

And you have conflicts for some reason. Rebase?

**Comment by brunowego** [comment]
Do you mean a `dist` folder? Users can use [wirede](https://github.com/taptapship/wiredep) to auto include the dependencies. The main attribute inside bower.json can be used for define the path of files.

**Comment by brunowego** [comment]
I understand what you mean, the current structure is not prepared for this.

**Comment by nkbt** [comment]
I've almost finished this one, but either Bower has some caching issue or
it is just an issue there - old package remains registered. If it won't fix
itself today, will contact bower support to manually handle this.

For now you should be able to use it as github dependency as
elementalui/elemental-dist

**Comment by nkbt** [comment]
@brunowego I am closing this PR, since `bower.json` now is in https://github.com/elementalui/elemental-dist repo.

**Pull request closed without merging**
