### PR TITLE
first draft of a jss button

### PR DESCRIPTION
**Pull request by kof**
This is not a full button rewrite, but rather a kickoff for a discussion #53

### CODE REVIEW

**Comment by kof** [comment]
question: why do we have classes 	.focus and .is-focus ?

**Comment by kof** [comment]
and how do we set disabled, there is no such a prop.

**Comment by kof** [comment]
currently we have a mixins/buttons.less which is actually used only from  Button.less as far I can see.

1. In js mixins are just functions
1.  Does it make sense to put functions which are used from jus one component into a  a separate dir?
1. How should we call the new mixins dir: e.g. `styles/functions/` or maybe everything is just `styles/utils/`?

**Comment by kof** [comment]
Also I would rather put styles directly near the component, I see at least 2 possibilities here:
1. every component has a dir: 
```
    src/components/button/
    src/components/button/Button.js
    src/components/button/style.js
    src/components/button/utils.js
```    

2. everything in one dir:

```
   src/components/

**Comment by kof** [comment]
I use in my projects dir per component structure so that every component contains everything specific to this component.

**Comment by kof** [comment]
Just realized we already have babel in use. Can we start using es6 features? Is it still es5 for consistency and waiting for a separate migration task?

**Comment by kof** [comment]
I ported the  gradients and realized we don't have a hex->argb converter, created an issue https://github.com/MoOx/color/issues/72 , does somebody want to help there with a PR?

**Comment by kof** [comment]
Also I think gradients are worth opensourcing as a separate repostory for e.g. jsstyles/gradients or something wdyt?

**Comment by kof** [comment]
ping @JedWatson lots of questions here)

**Comment by JedWatson** [comment]
Sorry for the delay - getting into hour 16 of a _really_ long day at work. Got a ridiculously ambitious deadline on a project :sleepy: 

Will get back to you as soon as I've had some sleep!

**Comment by kof** [comment]
@JedWatson you sleep def well!!!)

**Comment by nkbt** [comment]
:laughing:

**Comment by JedWatson** [comment]
Oh man, that's terrible. Sorry @kof! I'm about to jump on a plane to Nodevember, will get back to this asap. Setting a reminder for myself :)

**Comment by kof** [comment]
@JedWatson I will go with the structure I personally like to get a final proposal.

**Comment by JedWatson** [comment]
Sounds good @kof, thanks!

**Comment by cameronjroe** [comment]
Excited for this! Would love to see it in ES6 as well with potentially a decorator. Also thought I'd mention there's not currently a css file at all in the npm release.

**Comment by cameronjroe** [comment]
Any updates on this. I also found [react-container-query](https://github.com/d6u/react-container-query) which looks pretty cool for responsiveness.

**Comment by kof** [comment]
Sort of https://github.com/nikgraf/future-react-ui/issues/1

**Pull request closed without merging**
