### PR TITLE
Add limit option to pagination

### PR DESCRIPTION
**Pull request by MunGell**
Hey guys,

This is a small addition to pagination "element" that limits it in size if set.
Would be glad to hear your opinion on this.

Also, could you let me know where should I change the documentation and what is the process around unit-testing new functionality?

Many thanks

### CODE REVIEW

**Comment by jossmac** [comment]
Hi @MunGell,

Thanks for the PR! You can add documentation to the [Misc. Page](https://github.com/elementalui/elemental/blob/master/site/src/pages/Misc.js). We currently don't have any unit-testing in place - perhaps you could share your thoughts on that?

Unfortunately I can't merge it right away as it's a little buggy, or perhaps just doesn't work as expected. I thought it would follow the pagination paradigm where adding a `limit` of `5` would render a total of 5 pages with `...` that would take you to the last page, which would render something like:
`...` `11` `12` `13` `14` `15`

**Comment by MunGell** [comment]
Hey @jossmac 

For `limit` of `5` it renders total of 11 pages: 5 before current page + current page + 5 after current page. This way it ensures that pagination will always be symmetric to current page. I agree that this could be not the most obvious decision, suggestions are welcome.

I haven't implemented edge indicators like `...`, but let me know if it is a requirement - it should easy to add.

I am not too experienced with React unit-testing, but I see that you guys use Mocha (+ plugins) in other repositories, so may be it could be a good option to start with. I've used mocha/chai myself to test this logic (on a separate codebase).

**Comment by jossmac** [comment]
@MunGell thanks for getting back to me. Edge indicators would be terrific, if you don't mind :)

I think the term `limit` is a bit misleading if it means either side; I think it should be the total number of pages allowed (we can divide it where applicable). This screen capture didn't turn out very well, but hopefully it illustrates the odd behaviour I'm seeing:

pagination

@JedWatson care to weigh-in on unit testing?

**Comment by MunGell** [comment]
Cool, then I will update this PR with edge indicators in the next several days :)

I will also update `limit` logic and verify functionality on real pagination from example page.

**Comment by jossmac** [comment]
Thanks @MunGell, looking forward to it

**Comment by MunGell** [comment]
Hey @jossmac 

So, I've written some unit tests on the bug cases shown on the screencast above and most of them are actually working fine. In my case the difference between unit tests and actual results on the demo page was caused by wrong field type that I fixed in 903bce4.

I am going to work on the bug with `<Pagination currentPage=4 pageSize=36 total=130 limit=1>` case and add more edge-case tests just to be sure it is robust enough.

**Comment by jossmac** [comment]
@MunGell sounds good! Thank you for being proactive about this :)

**Comment by MunGell** [comment]
@jossmac Could you please take a look at the current state of the pagination in this PR?

**Comment by jossmac** [comment]
@MunGell sorry mate, I thought it was incomplete:

> I am going to work on the bug with `<Pagination currentPage=4 pageSize=36 total=130 limit=1>` case and add more edge-case tests just to be sure it is robust enough.

So it's ready for review now?

**Comment by jossmac** [comment]
Just reviewed it - this is fantastic! Thank you :)

**Comment by MunGell** [comment]
Yeah, fixed that bug and added edge indicators :)
Thanks!

**Pull request merged**
