### PR TITLE
Add CircleCI

### PR DESCRIPTION
**Pull request by nkbt**
Does linting for now and package build (automatically on npm install).

Better then nothing =)

### CODE REVIEW

**Comment by nkbt** [comment]
See build results for this PR: https://circleci.com/gh/nkbt/elemental/2

Shows lint warnings (but does not break the build). if there are lint errors - will break.

**Comment by nkbt** [comment]
Needs project owner to allow access, so it can hook up with all PRs and commits

**Comment by JedWatson** [comment]
Good call @nkbt, thanks. Not sure why you don't already have access, I'm setting it up now.

**Comment by nkbt** [comment]
Hmm, for some reason I still can't add elemental project to circleci

**Pull request merged**
