### PR TITLE
added legit-tests

### PR DESCRIPTION
**Pull request by zackify**
This is a copy of #58 but using legit tests. It could be a little better, some things could be broken into a function and be reusable, but I am looking for feedback. What do you think @JedWatson?

### CODE REVIEW

**Comment by benigeri** [comment]
@zackify nice tests

**Comment by zackify** [comment]
@benigeri thanks :)

**Comment by zackify** [comment]
@JedWatson status?

**Comment by MunGell** [comment]
:+1: nice work

**Comment by JedWatson** [comment]
Thanks @zackify - we ended up going wiht #116 so I'm closing this, really appreciate the contribution though!

**Pull request closed without merging**
