### PR TITLE
enable custom password validator in PasswordInputGroup

### PR DESCRIPTION
**Pull request by teaualune**
It would be nice to set the password validator by passing it via `props` to fit various application requirements.
Moreover, I noticed that the feature can be utilized to build confirm password field, where an example is given in the `sites/Forms.js`.

### CODE REVIEW

**Comment by inooid** [comment]
@teaualune Ah right, thanks! Learning new things every day :sunny:

**Comment by teaualune** [comment]
@inooid :smiley:

**Comment by JedWatson** [comment]
This looks good @teaualune, thanks!

**Comment by teaualune** [comment]
@JedWatson thanks! :coffee:

**Pull request merged**
